/**
 * Generate participant-facing contract references from executable sources.
 *
 * Sources of truth:
 * - signal fields: schema/signal.schema.json
 * - manifest constraints: packages/shared moduleManifestSchema (Zod)
 * - UI SDK exports/signatures: packages/plugin-sdk/src/index.ts + TypeScript
 * - loader helpers: wcc_impact.__all__ + inspect.signature()
 */

import { execFileSync } from "node:child_process";
import {
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import process from "node:process";
import ts from "typescript";
import { z } from "zod";
import { moduleManifestSchema } from "../packages/shared/src/module";

type JsonObject = Record<string, unknown>;

const root = path.resolve(import.meta.dirname, "..");
const outputDir = path.join(root, "docs", "generated");
const checkOnly = process.argv.includes("--check");
const generatedHeader =
  "<!-- Generated by scripts/gen-contract-docs.ts. Do not edit by hand. -->";

function object(value: unknown): JsonObject {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as JsonObject)
    : {};
}

function md(value: unknown): string {
  return String(value ?? "")
    .replaceAll("|", "\\|")
    .replaceAll("\n", " ")
    .trim();
}

function jsonType(schemaValue: unknown, pathHint = ""): string {
  const schema = object(schemaValue);
  if (pathHint === "ui" || pathHint.endsWith(".ui")) return "lazy page import";
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (Array.isArray(schema.type)) return schema.type.map(String).join(" | ");
  if (schema.type === "array") return `array<${jsonType(schema.items, `${pathHint}[]`)}>`;
  if (typeof schema.type === "string") return schema.type;
  return "runtime value";
}

function constraints(schemaValue: unknown): string {
  const schema = object(schemaValue);
  const parts: string[] = [];
  if (schema.format) parts.push(String(schema.format));
  if (schema.const !== undefined) parts.push(`exactly: ${JSON.stringify(schema.const)}`);
  if (Array.isArray(schema.enum)) parts.push(`one of: ${schema.enum.join(", ")}`);
  if (schema.pattern) parts.push(`pattern: ${schema.pattern}`);
  if (schema.minLength !== undefined) parts.push(`min ${schema.minLength} chars`);
  if (schema.maxLength !== undefined) parts.push(`max ${schema.maxLength} chars`);
  if (schema.minimum !== undefined) parts.push(`≥ ${schema.minimum}`);
  if (schema.exclusiveMinimum !== undefined) parts.push(`> ${schema.exclusiveMinimum}`);
  if (schema.maximum !== undefined) parts.push(`≤ ${schema.maximum}`);
  if (schema.exclusiveMaximum !== undefined) parts.push(`< ${schema.exclusiveMaximum}`);
  if (schema.default !== undefined) parts.push(`default: ${JSON.stringify(schema.default)}`);
  if (schema.type === "array") {
    const itemConstraints = constraints(schema.items);
    if (itemConstraints !== "—") parts.push(`items: ${itemConstraints}`);
  }
  return parts.join("; ") || "—";
}

function schemaTable(schemaValue: unknown, prefix = ""): string {
  const schema = object(schemaValue);
  const properties = object(schema.properties);
  const required = new Set(
    Array.isArray(schema.required) ? schema.required.map(String) : [],
  );
  return Object.entries(properties)
    .map(([name, value]) => {
      const fieldPath = prefix ? `${prefix}.${name}` : name;
      const property = object(value);
      return `| \`${md(name)}\` | ${required.has(name) ? "yes" : "no"} | ${md(
        jsonType(property, fieldPath),
      )} | ${md(constraints(property))} | ${md(property.description || "—")} |`;
    })
    .join("\n");
}

function signalFields(): string {
  const schema = JSON.parse(
    readFileSync(path.join(root, "schema", "signal.schema.json"), "utf8"),
  );
  return `${generatedHeader}

# Signal fields

Authoritative source: [\`schema/signal.schema.json\`](../../schema/signal.schema.json).
“Required” means required in a loader insert; database-generated fields remain optional.

| Field | Required | Type | Constraints | Description |
|---|---:|---|---|---|
${schemaTable(schema)}
`;
}

function manifestReference(): string {
  const schema = z.toJSONSchema(moduleManifestSchema, {
    unrepresentable: "any",
  }) as JsonObject;
  const properties = object(schema.properties);
  const sections: string[] = [];

  for (const name of ["pages", "widgets", "homeStat"]) {
    const property = object(properties[name]);
    const nested =
      name === "pages" || name === "widgets"
        ? object(object(property.items).properties)
        : object(property.properties);
    const nestedSchema =
      name === "pages" || name === "widgets"
        ? object(property.items)
        : property;
    if (Object.keys(nested).length === 0) continue;
    sections.push(`
## \`${name}\` fields

| Field | Required | Type | Constraints | Description |
|---|---:|---|---|---|
${schemaTable(
  nestedSchema,
  name === "pages" || name === "widgets" ? `${name}[]` : name,
)}
`);

    if (name === "widgets") {
      for (const sizeName of ["defaultSize", "minSize", "maxSize"]) {
        const sizeSchema = object(nested[sizeName]);
        if (Object.keys(object(sizeSchema.properties)).length === 0) continue;
        sections.push(`
## \`widgets[].${sizeName}\` fields

| Field | Required | Type | Constraints | Description |
|---|---:|---|---|---|
${schemaTable(sizeSchema, `widgets[].${sizeName}`)}
`);
      }

      const optionsSchema = object(nested.options);
      const optionVariants = object(optionsSchema.items).oneOf;
      if (Array.isArray(optionVariants)) {
        for (const variant of optionVariants) {
          const variantSchema = object(variant);
          const typeSchema = object(object(variantSchema.properties).type);
          const optionType = String(typeSchema.const ?? "option");
          sections.push(`
## \`widgets[].options\` — ${optionType}

| Field | Required | Type | Constraints | Description |
|---|---:|---|---|---|
${schemaTable(variantSchema, "widgets[].options[]")}
`);
          if (optionType === "select") {
            const choicesSchema = object(
              object(object(variantSchema.properties).choices).items,
            );
            sections.push(`
## \`widgets[].options[].choices\`

| Field | Required | Type | Constraints | Description |
|---|---:|---|---|---|
${schemaTable(choicesSchema, "widgets[].options[].choices[]")}
`);
          }
        }
      }
    }
  }

  return `${generatedHeader}

# Module manifest reference

Authoritative source: \`moduleManifestSchema\` in
[\`packages/shared/src/module.ts\`](../../packages/shared/src/module.ts). The same validator
runs during \`pnpm gen\`.

| Field | Required | Type | Constraints | Description |
|---|---:|---|---|---|
${schemaTable(schema)}
${sections.join("")}
`;
}

function symbolKind(symbol: ts.Symbol): string {
  if (symbol.flags & ts.SymbolFlags.Interface) return "interface";
  if (symbol.flags & ts.SymbolFlags.TypeAlias) return "type";
  if (symbol.flags & ts.SymbolFlags.Class) return "class";
  if (symbol.flags & ts.SymbolFlags.Function) return "function";
  return "value";
}

function pluginSdkReference(): string {
  const configPath = path.join(root, "packages", "plugin-sdk", "tsconfig.json");
  const config = ts.readConfigFile(configPath, ts.sys.readFile);
  if (config.error) {
    throw new Error(ts.flattenDiagnosticMessageText(config.error.messageText, "\n"));
  }
  const parsed = ts.parseJsonConfigFileContent(
    config.config,
    ts.sys,
    path.dirname(configPath),
  );
  const program = ts.createProgram(parsed.fileNames, parsed.options);
  const checker = program.getTypeChecker();
  const indexPath = path.join(root, "packages", "plugin-sdk", "src", "index.ts");
  const source = program.getSourceFile(indexPath);
  if (!source) throw new Error(`TypeScript program did not load ${indexPath}`);
  const moduleSymbol = checker.getSymbolAtLocation(source);
  if (!moduleSymbol) throw new Error("Could not resolve @wcc-impact/plugin-sdk exports");

  const core: Array<{ name: string; kind: string; signature: string; summary: string }> = [];
  const shared: Array<{ name: string; kind: string }> = [];
  const ui: string[] = [];

  for (const exported of checker.getExportsOfModule(moduleSymbol)) {
    const target =
      exported.flags & ts.SymbolFlags.Alias
        ? checker.getAliasedSymbol(exported)
        : exported;
    const declaration = target.valueDeclaration ?? target.declarations?.[0];
    if (!declaration) continue;
    const sourcePath = declaration.getSourceFile().fileName.replaceAll("\\", "/");
    const name = exported.getName();
    const kind = symbolKind(target);

    if (sourcePath.includes("/packages/ui/")) {
      ui.push(name);
      continue;
    }
    if (sourcePath.includes("/packages/shared/")) {
      shared.push({ name, kind });
      continue;
    }
    if (!sourcePath.includes("/packages/plugin-sdk/")) continue;

    const type = checker.getTypeOfSymbolAtLocation(target, declaration);
    const signatures = checker.getSignaturesOfType(type, ts.SignatureKind.Call);
    const signature = signatures.length
      ? signatures
          .map(
            (item) =>
              `${name}${checker.signatureToString(
                item,
                declaration,
                ts.TypeFormatFlags.UseAliasDefinedOutsideCurrentScope,
              )}`,
          )
          .join("<br>")
      : kind;
    const summary = ts
      .displayPartsToString(target.getDocumentationComment(checker))
      .split("\n\n", 1)[0]
      .replaceAll("\n", " ");
    core.push({ name, kind, signature, summary });
  }

  core.sort((a, b) => a.name.localeCompare(b.name));
  shared.sort((a, b) => a.name.localeCompare(b.name));
  ui.sort((a, b) => a.localeCompare(b));

  return `${generatedHeader}

# \`@wcc-impact/plugin-sdk\` public reference

Authoritative source: the package barrel
[\`packages/plugin-sdk/src/index.ts\`](../../packages/plugin-sdk/src/index.ts). Module UIs
may import these exports (plus React); they must not import dashboard internals.

## Platform functions, hooks, components, and types

| Export | Kind | Current signature | Source summary |
|---|---|---|---|
${core
  .map(
    (item) =>
      `| \`${md(item.name)}\` | ${item.kind} | \`${md(item.signature)}\` | ${md(
        item.summary || "—",
      )} |`,
  )
  .join("\n")}

## Re-exported shared contracts

${shared.map((item) => `- \`${item.name}\` (${item.kind})`).join("\n")}

## Re-exported UI kit

${ui.map((name) => `- \`${name}\``).join("\n")}
`;
}

interface PythonApi {
  functions: Array<{ name: string; signature: string; summary: string }>;
  classes: Array<{ name: string; summary: string }>;
  constants: Array<{ name: string; value: string }>;
}

function pythonReference(): string {
  const raw = execFileSync(
    "uv",
    ["run", "python", path.join(root, "scripts", "extract-python-api.py")],
    { cwd: root, encoding: "utf8" },
  );
  const api = JSON.parse(raw) as PythonApi;
  return `${generatedHeader}

# \`wcc_impact\` public reference

Authoritative source: \`wcc_impact.__all__\` and the runtime signatures in
[\`packages/wcc-impact-platform-py/src/wcc_impact\`](../../packages/wcc-impact-platform-py/src/wcc_impact).
The package reads the root \`.env\` and attaches the current team's
\`MODULE_TOKEN\` to writes.

## Functions

| Function | Current signature | Summary |
|---|---|---|
${api.functions
  .map(
    (item) =>
      `| \`${md(item.name)}\` | \`${md(item.signature)}\` | ${md(item.summary || "—")} |`,
  )
  .join("\n")}

## Public classes

${api.classes.map((item) => `- \`${item.name}\` — ${md(item.summary || "—")}`).join("\n")}

## Public constants

${api.constants.map((item) => `- \`${item.name}\` = \`${md(item.value)}\``).join("\n")}
`;
}

const outputs = new Map<string, string>([
  ["signal-fields.md", signalFields()],
  ["manifest-reference.md", manifestReference()],
  ["plugin-sdk-reference.md", pluginSdkReference()],
  ["python-api-reference.md", pythonReference()],
]);

mkdirSync(outputDir, { recursive: true });
const stale: string[] = [];
for (const [name, content] of outputs) {
  const target = path.join(outputDir, name);
  const normalized = content.trimEnd() + "\n";
  if (checkOnly) {
    let current = "";
    try {
      current = readFileSync(target, "utf8");
    } catch {
      // Missing generated files are stale.
    }
    if (current !== normalized) stale.push(path.relative(root, target));
  } else {
    writeFileSync(target, normalized);
    console.log(`generated ${path.relative(root, target)}`);
  }
}

if (stale.length > 0) {
  console.error(
    `Generated contract documentation is stale:\n${stale
      .map((name) => `  - ${name}`)
      .join("\n")}\nRun: pnpm docs:generate`,
  );
  process.exitCode = 1;
} else if (checkOnly) {
  console.log("Generated contract documentation is current.");
}
